let Magias = [
    {
        nome : "Alarme",
        descricao : "Você cria uma barreira protetora invisível que detecta qualquer criatura que tocar ou entrar na área protegida. Ao lançar a magia, você pode escolher quais criaturas podem entrar na área sem ativar seus efeitos. Alarme pode emitir um aviso telepático ou sonoro, decidido quando a magia é lançada. Um aviso telepático alerta apenas você, inclusive acordando-o se estiver dormindo, mas apenas se estiver a até 1km da área protegida. Um aviso sonoro alerta todas as criaturas em alcance longo.",
        custo : "1pm",
        execucaco : "Padrão",
        alcance : "Curto",
        alvo : null,
        area : "Esfera com 9m de raio",
        duracao: "1 dia",
        Truque: null,
        mana1: "+2 PM: muda o alcance para pessoal. A área é emanada a partir de você.",
        mana2: "+5 PM: além do normal, você também percebe qualquer efeito de adivinhação que seja usado dentro da área ou atravesse a área. Você pode fazer um teste oposto de Misticismo contra quem usou o efeito; se passar, tem um vislumbre de seu rosto e uma ideia aproximada de sua localização (“três dias de viagem ao norte”, por exemplo).",
        mana3: "+9 PM: muda a duração para um dia ou até ser descarregada e a resistência para Vontade anula. Quando um intruso entra na área, você pode descarregar a magia. Se o intruso falhar na resistência, ficará paralisado por 1d4 rodadas. Além disso, pelas próximas 24 horas você e as criaturas escolhidas ganham +10 em testes de Sobrevivência para rastrear o intruso.",
        mana4: null,
        mana5: null,
        tags: "Abjuração Abjur"
    },
    {
        nome : "Armadura Arcana",
        descricao : "Esta magia cria uma película protetora invisível, mas tangível, fornecendo +5 na Defesa. Esse bônus é cumulativo com outras magias, mas não com bônus fornecido por armaduras.",
        custo : "1pm",
        execucaco : "Padrão",
        alcance : "Pessoal",
        alvo : "Você",
        area : null,
        duracao: "Cena",
        Truque: null,
        mana1: "+1 PM: muda a execução para reação. Em vez do normal, você cria um escudo mágico que fornece +5 na Defesa contra o próximo ataque que sofrer (cumulativo com o bônus fornecido pelo efeito básico desta magia e armaduras).",
        mana2: "+2 PM: aumenta o bônus na Defesa em +1.",
        mana3: "+2 PM: muda a duração para um dia.",
        mana4: null,
        mana5: null,
        tags: "Abjuração Abjur"
    },
    {
        nome : " Resistência a Energia",
        descricao : "Ao lançar esta magia, escolha entre ácido, eletricidade, fogo, frio, luz ou trevas. O alvo recebe redução de dano 10 contra o tipo de dano escolhido.",
        custo : "1pm",
        execucaco : "Padrão",
        alcance : "Toque",
        alvo : "1 Criatura",
        area : null,
        duracao: "Cena",
        Truque: null,
        mana1: "+2 PM: aumenta a redução de dano em +5.",
        mana2: "+2 PM: muda a duração para um dia. Requer 2º círculo.",
        mana3: "+5 PM: muda o alcance para curto e o alvo para criaturas escolhidas. Requer 3º círculo.",
        mana4: "+5 PM: muda o efeito para redução de dano contra todos os tipos listados na magia. Requer 3º círculo.",
        mana5: "+9 PM: muda o efeito para imunidade a um tipo listado na magia. Requer 4º círculo.",
        tags: "Abjuração Abjur"
    },
    {
        nome : "Tranca Arcana",
        descricao : "Esta magia tranca uma porta ou outro item que possa ser aberto ou fechado (como um baú, caixa etc.), aumentando a CD de testes de Força ou Ladinagem para abri-lo em +10. Você pode abrir livremente sua própria tranca sem problemas. Componente material: chave de bronze no valor de T$ 25.",
        custo : "1pm",
        execucaco : "Padrão",
        alcance : "Toque",
        alvo : "1 Objeto Grande ou Menor",
        area : null,
        duracao: "Permanente",
        Truque: "muda o alcance para curto. Em vez do normal, pode abrir ou fechar um objeto de tamanho Médio ou menor, como uma porta ou baú. Não afeta objetos trancados.",
        mana1: "muda o alcance para curto e a duração para instantânea. Em vez do normal, a magia abre portas, baús e janelas trancadas, presas, barradas ou protegidas por Tranca Arcana (o efeito é dissipado) a sua escolha. Ela também afrouxa grilhões e solta correntes.",
        mana2: "aumenta a CD para abrir o alvo em +5.",
        mana3: "muda o alvo para 1 objeto de qualquer tamanho, podendo afetar até mesmo os portões de um castelo. Requer 3º círculo.",
        mana4: null,
        mana5: null,
        tags: "Abjuração Abjur"
    }
];
